# dev dependent services
version: '3.1'

services:
  db:
    image: mariadb
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_HOST: '127.0.0.1'
      MYSQL_USER: test
      MYSQL_PASSWORD: test_pass
    volumes:
      - "$HOME/volume/db:/var/lib/mysql"