# dev dependent services
version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
      MYSQL_ROOT_HOST: '%'
    volumes:
      - "$HOME/volume/db:/var/lib/mysql"

  app:
    image: firemark-app
    depends_on: 
      - "db"
    restart: always
    ports:
      - 8000:8000